Update test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -256,6 +256,12 @@ jobs:
           dir_$(CONFIG_FIRMWARE_INCLUDE_NFQWS2)\t\t+= nfqws2/' "$mf"
           fi
           grep 'nfqws' "$mf" || true
+          
+      - name: Check nfqws2 in romfs
+        run: |
+          cd padavan-ng-hadzhioglu/trunk
+          echo "=== search nfqws2 in romfs ==="
+          find romfs -maxdepth 8 -type f -iname 'nfqws2*' -o -iname 'zapret2*' -print || echo "nfqws2 files not found in romfs"
 
 #============================================================================
 
